language: objective-c
osx_image: xcode7.3
xcode_project: PaginatedListViewModel.xcodeproj 
xcode_scheme: PaginatedListViewModel 
xcode_sdk: iphonesimulator9.3
before_install:
  - carthage version
before_script:
  - carthage bootstrap --platform ios

